# -*- coding: utf-8 -*-
"""10DemoScatterQtl.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zUBwkNzM4e2cg_2JY12FIYwxAuwZH2XA

<pre>
1. Load the demo dataset in dataframe object df
2. Detect the outlier using ScatterPlot
3. Handle the outlier using Quantile based flooring and capping
  (Hint: the outlier is capped at a certain value above the 90th percentile value
or floored at a factor below the 10th percentile value)
</pre>
"""

import pandas as pd
import numpy as np

df = pd.read_csv('demo.csv')
df

#plot the scatter plot
cols = ['math score',
 'reading score',
 'writing score',
 'placement score',
        'placement offer count'
  ]
cols

import matplotlib.pyplot as plt

plt.scatter(df['placement score'], df['placement offer count'])

df_stud = df
ninetieth_percentile = np.percentile(df_stud['math score'], 90)
b = np.where(df_stud['math score']>ninetieth_percentile, ninetieth_percentile, df_stud['math score'])
print("New array:",b)
df_stud.insert(1,"m score",b,True)
df_stud