# -*- coding: utf-8 -*-
"""11DemoMeanMode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f-xhhglUw3mVoNHCi6IEdRZDpIGM-ZIG

<pre>
1. Load the demo dataset in dataframe object df
2. Detect the outlier using Z-score
3. replace the outliers with the median value.
</pre>
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

df = pd.read_csv('demo.csv')
df

# detect outlier using z - score
cols = ['math score',
 'reading score',
 'writing score',
 'placement score',
        'placement offer count'
  ]
cols

z = np.abs(stats.zscore(df['placement score']))
z

th = 0.18
th

outliers = np.where(z < th)

df.boxplot('placement score')

zsc = np.abs(stats.zscore(df))
zsc

# ot = (zsc > 3).any(axis = 1)
ot = (zsc > 3)
ot

df[ot] = df.median()

df

ot