# -*- coding: utf-8 -*-
"""12DemoIQR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/140AFMIP8gMhJ48mPlPjc-GzJSx72tQJm

<pre>
1. Load the demo dataset in dataframe object df
2. Detect the outlier using Inter Quantile Range(IQR)
3. remove the outliers from the dataset.
</pre>
"""

import pandas as pd
import numpy as np

df = pd.read_csv('demo.csv')
df

rscore = sorted(df['reading score'])

df.head()

rscore

q1 = np.percentile(rscore, 25)

q1

q3 = np.percentile(rscore, 75)
q3

IQR = q3 - q1

lower_bound = q3 - 1.5 * IQR
upper_bound = q3 + 1.5 * IQR

lower_bound, upper_bound

outliers = df[(df['reading score'] < lower_bound) | (df['reading score'] > upper_bound)]

outliers

ninetieth_percentile = np.percentile(df['reading score'], 90)
df.loc[df['reading score'] > upper_bound, 'reading score'] = ninetieth_percentile

# Print the DataFrame with replaced outliers
df.head()

outliers = []
for i in rscore:
   if (i < 56 and i > 92):
    outliers.append(i)
outliers

import seaborn as sns
sns.boxplot(df['reading score'])

for i in outliers:
  df.drop(i, inplace= True)
df

sns.boxplot(df['reading score'])