# -*- coding: utf-8 -*-
"""13MallCustomer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z3RR8QXX7SMCm5vCfGrx3oHsYzPGU_Rg

<pre>
1. Load the MallCustomer dataset in dataframe object df
2. Display summary statistics
(mean, median, minimum, maximum, standard deviation) for a dataset for each column
3. Display Measures of Dispersion
( Mean Absolute Deviation, Variance, Standard Deviation, Range, Quartiles, Skewness)
4. if your categorical variable is age groupsa nd quantitative variable is income, then provide summary statistics
(minimum and maximum) of income
grouped by the age groups
</pre>
"""



import pandas as pd
import numpy as np
import seaborn as sns

df = pd.read_csv('Mall_Customers.csv')
df

df.describe()

df.loc[:, 'Age'].median()

df.min()

new_df = df.drop(['Genre'], axis = 1)

new_df

new_df.median()

new_df.mode()

mean = np.mean(new_df)
mean

#mean absolute deviation
mean_abs_dev = np.mean(abs(new_df - mean))
mean_abs_dev

new_df.var()

new_df.std()

np.percentile(new_df, 25)

new_df.skew()

# summary stats
df.groupby(['Genre'])['Age'].mean()