# -*- coding: utf-8 -*-
"""18TitanicDataset.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14y6EuWFeGVQNW0K-nS1H6u3_XAI20tyB

<pre>1. Use the inbuilt dataset 'titanic'.
Use the Seaborn library to see if we can find any patterns in the data.
2. Write a code to check how the price of the ticket (column name: 'fare')
for each passenger is distributed by plotting a histogram</pre>
"""

import pandas as pd
import seaborn as sns

df = sns.load_dataset('titanic')

df

df.isna().sum()

sns.histplot(df['fare'], bins = 10, kde= True, fill= True)