# -*- coding: utf-8 -*-
"""1datawrangling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1unzFyTmPuMj2YbSF8RA9H7cf-GOwqaV3

<h1>Assignment no 1</h1>
<pre>1. Locate open Iris dataset from the URL csv_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
2. Perform the following operation on dataset
a) Display total no of rows and column
b) Display type of each column
c) Sort the data in descending order , by considering column sepal.length
d) Slice the data: 11 to 20 rows, and only two columns, sepal.length and Species
e) rename the column Species to Type</pre>
"""

#import all neccessary modules
import pandas as pd

#import the dataset from url
csv_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
columns = ['sepal.length', 'sepal.width', 'petal.length', 'petal.width', 'Species']
df = pd.read_csv(csv_url, header = None, names = columns)

df

df.columns

#a => no of rows and columns
rows, cols = df.shape

print("Rows = ", rows, "\tColumns = ", cols)

#b => display the type of each cols

df.dtypes

#c => sort the values using column sepal.length
df.sort_values(by = 'sepal.length', ascending = False)

#d => display the datat only of the 10 to 20
df.loc[10:19, ['sepal.length', 'Species']]

#e => rename the species column to type
df.rename({'Species':'Type'}, inplace = True)
df