# -*- coding: utf-8 -*-
"""20irisFlowerComp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RjeAK6PKFFWzCwRfmMBiJv8mqMRfQyg2

Download the Iris flower dataset or any other dataset into a DataFrame. (e.g.,
https://archive.ics.uci.edu/ml/datasets/Iris ). Scan the dataset and give the inference as:
1. List down the features and their types (e.g., numeric, nominal) available in the dataset.
2. Create a histogram for each feature in the dataset to illustrate the feature distributions.
3. Create a box plot for each feature in the dataset.
4. Compare distributions and identify outliers.
"""

import pandas as pd
import seaborn as sn
import matplotlib.pyplot as plt

df = sn.load_dataset('iris')

df.head()

df.dtypes

fig, axs = plt.subplots(2, 2, figsize=(10, 10))
axs = axs.flatten()

for i, feature in enumerate(df.columns[:-1]):
    sn.histplot(data=df, x=feature, kde=True, ax=axs[i])
    axs[i].set_title(f"Histogram of {feature}")

# plt.tighten_layout()
plt.suptitle('Histograms of Features in Iris Dataset')
plt.show()

plt.figure(figsize=(12, 8))
for i, feature in enumerate(df.columns[:-1]):
    plt.subplot(2, 2, i + 1)
    sn.boxplot(data=df, x=feature)
    plt.title(f"Box Plot of {feature}")

plt.tight_layout()
plt.suptitle('Box Plots of Features in Iris Dataset')
plt.show()

for i, feature in enumerate(df.columns[:-1]):
  sn.boxplot(x= feature, data = df)

