# -*- coding: utf-8 -*-
"""2studentDataset.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PWDGELiX4cJAFz9xqnb4XlN8-Uyw8Ngk

<pre>
Consider the given dataset StudentsPerformanceTest1
1. Check that is there any missing values in dataframe as a whole
2. is there any missing values across each column
3. count of missing values across each column
4. count row wise missing value
5. count of missing values of a gender column.
6. groupby count of missing values of a column , consider column gender and score
7. replace the missing value of score column with average value of the column

</pre>
"""

import pandas as pd

csv_url = "StudentsPerformanceTest1.csv"
df = pd.read_csv(csv_url, na_values=['na','Na'])

df

#1 = > check the is null value in whole df
df.isnull().values.any()

#2 => check there is null value in col
df.isna().sum()

#3 => check there is missing value in col
df.isna().sum()

#4 => count row wise missing values
df.isna().sum(axis = 1)

# Replace missing values in the "placement score" column with the average
average_placement_score = df['Placement Score'].mean()
df['Placement Score'].fillna(average_placement_score, inplace=True)
print("\nPlacement score column after replacing missing values with average:")
print(df['Placement Score'].head())

df.isna().sum()

missing_gender = df['gender'].isnull().sum() if 'gender' in df.columns else 0
missing_score = df['Placement Score'].isnull().sum()

# Group the data based on missing values in the 'gender' and 'placement score' columns
# Since the 'gender' column may not be in the data, we may need to check its existence
if 'gender' in df.columns:
    df['missing_gender'] = df['gender'].isnull().astype(int)

df['missing_score'] = df['Placement Score'].isnull().astype(int)

# Group by count of missing values in 'gender' and 'score' columns
grouped = df.groupby(['missing_gender', 'missing_score']).size()

print("Grouped data based on missing values in 'gender' and 'placement score' columns:")
print(grouped)

df

