# -*- coding: utf-8 -*-
"""3LabelEncodingIris.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15WSrkSuAI4loNRKbMEVNk9OG2vnULlRN

<pre>
1. Locate open Iris dataset from the URL csv_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
2. Perform the label encoding , by considering Species as target variable.
</pre>
"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder

csv_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
cols = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'Species']
df = pd.read_csv(csv_url, names = cols)

df

df.columns

le = LabelEncoder()

df['Species'] = le.fit_transform(df['Species'])

df['Species']

df.head()

df['Species'].unique()