# -*- coding: utf-8 -*-
"""4irisOneHotEncode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bJpL-hHhIYUWghc6EenUK2ia1do9vEDr

<pre>
1. Locate open Iris dataset from the URL csv_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
2. Perform the One Hot encoding , by considering Species as target variable.

</pre>
"""

import pandas as pd
from sklearn.preprocessing import OneHotEncoder

csv_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
cols = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'Species']
df = pd.read_csv(csv_url, names = cols)

df

df['Species'].unique()

ohe = OneHotEncoder(handle_unknown = 'ignore',sparse_output= False).set_output(transform = 'pandas')
# ohe = OneHotEncoder()
df_transform = ohe.fit_transform(df[['Species']])

df_transform.head()

# concate the df
df = pd.concat([df, df_transform], axis = 1).drop(columns = ['Species'])

df.head()

ohe  = OneHotEncoder(handle_unknown='ignore', sparse_output=False).set_output(transform = 'pandas')