# -*- coding: utf-8 -*-
"""8AcedemicPerformance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10G0Ze7It634-gFkgb3kUo6rIouGFnqJ8

<pre>
1. Load the Academic Performance dataset in data frame object.
2. Check null values in the dataset.
3. Count the number of null values in complete data set (Hint: eplace the null values with standard null value NaN)
4. Dropping rows with at least 1 null value
5. Dropping rows if all values in that row are missing
6. Dropping columns with at least 1 null value.
7. Dropping Rows with at least 1 null value in CSV file
</pre>
"""

import pandas as pd

df = pd.read_csv('AcademicPerformance.csv', header= None, na_values=['na','Na'])
df

#Check null values in the dataset.
df.isna().sum()

ndf = df #Copy the dataset

# Dropping rows with at least 1 null value
ndf.dropna()

ndf.dropna(how = 'all')
# Dropping rows if all values in that row are missing

ndf.dropna(axis = 1)
# Dropping columns with at least 1 null value.

# Dropping Rows with at least 1 null value in CSV file
ndf.dropna(axis = 0, how = 'any')