# -*- coding: utf-8 -*-
"""9demoDfBox_Qt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GIQJ-UsANk9Yar80BksSEw4shqBdFhN6

<pre>
1. Load the demo dataset in dataframe object df
2. Detect the outlier using BoxPlot.
3. Handle the outlier using Quantile based flooring and capping
  (Hint: the outlier is capped at a certain value above the 90th percentile value
or floored at a factor below the 10th percentile value)
</pre>
"""

import pandas as pd
import numpy as np

df = pd.read_csv('demo.csv')
df.head(10)

#plot the box plot
cols = ['math score',
 'reading score',
 'writing score',
 'placement score',
        'placement offer count'
  ]
cols

df.boxplot(cols)

#print the outlier

print(np.where(df['math score'] > 90))

np.where(df['reading score'] < 25)

np.where(df['writing score'] < 25)

np.where(df['placement score'] < 50)

#quantile based flooring and capping
df_stud=df
ninetieth_percentile = np.percentile(df_stud['math score'], 90)
b = np.where(df_stud['math score']>ninetieth_percentile ,ninetieth_percentile, df_stud['math score'])
print("New array:",b)

df_stud.insert(1,"m score",b,True)
df_stud

df['math score'].skew()

df['m score'].skew()